behaviors:
  Push:
    trainer_type: ppo
    hyperparameters:
      batch_size: 400
      buffer_size: 4000
      learning_rate: 1.0e-5
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.0
    max_steps: 1000000
    time_horizon: 100
    summary_freq: 35000
